[package]
name = "tcpip"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
pnet = "0.34.0"
libc = "0.2.154"
anyhow = "1.0.82"
nom = "7.1.3"
log = "0.4.21"
rand = "0.9.0-alpha.1"
